# Generated by Django 3.2.19 on 2023-06-13 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='patient_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_id', models.IntegerField()),
                ('p_name', models.CharField(max_length=100)),
                ('p_email', models.EmailField(max_length=100)),
                ('p_phone_number', models.CharField(max_length=10)),
                ('p_DOB', models.DateField(max_length=8)),
                ('p_address', models.CharField(max_length=100)),
                ('p_sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('p_blood_group', models.CharField(max_length=10)),
                ('p_weight', models.IntegerField()),
                ('p_height', models.IntegerField()),
                ('p_previous_medical_history', models.CharField(max_length=100)),
                ('p_smoking', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
                ('p_alcohol', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
                ('p_drugs', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
