# Generated by Django 3.2.19 on 2023-06-16 05:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_id', models.IntegerField()),
                ('case_name', models.CharField(max_length=100)),
                ('case_remarks', models.CharField(max_length=700)),
                ('follow_up_visit', models.DateTimeField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('doctor_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated', '-created'],
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('patient_name', models.CharField(max_length=100)),
                ('patient_email', models.EmailField(max_length=100)),
                ('patient_phone_number', models.CharField(max_length=10)),
                ('patient_dob', models.DateField(max_length=8)),
                ('patient_address', models.CharField(max_length=100)),
                ('patient_sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('patient_blood_group', models.CharField(max_length=10)),
                ('patient_weight', models.IntegerField()),
                ('patient_height', models.IntegerField()),
                ('patient_blood_pressure', models.IntegerField(null=True)),
                ('patient_body_temprature', models.IntegerField(null=True)),
                ('patient_pulse', models.IntegerField(null=True)),
                ('patient_previous_medical_history', models.CharField(max_length=100)),
                ('patient_smoking', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
                ('patient_alcohol', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
                ('patient_drugs', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('doctor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated', '-created'],
            },
        ),
        migrations.CreateModel(
            name='Medications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medication_id', models.IntegerField()),
                ('medication_name', models.CharField(max_length=100)),
                ('medication_dosage', models.CharField(max_length=700)),
                ('medication_duration', models.IntegerField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('case_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.case')),
                ('doctor_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('patient_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.patient')),
            ],
            options={
                'ordering': ['-updated', '-created'],
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_designation', models.CharField(max_length=100)),
                ('doctor_education', models.CharField(max_length=100)),
                ('doctor_hospital', models.CharField(max_length=100)),
                ('doctor_location', models.CharField(max_length=100)),
                ('doctor_phone_number', models.CharField(max_length=10)),
                ('doctor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='case',
            name='patient_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.patient'),
        ),
    ]
