# Generated by Django 3.2.19 on 2023-06-13 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rename_patient_details_patient'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='p_address',
            new_name='patient_address',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='p_alcohol',
            new_name='patient_alcohol',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='p_blood_group',
            new_name='patient_blood_group',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='p_DOB',
            new_name='patient_dob',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='p_drugs',
            new_name='patient_drugs',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='p_email',
            new_name='patient_email',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='p_height',
            new_name='patient_height',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='p_id',
            new_name='patient_id',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='p_name',
            new_name='patient_name',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='p_phone_number',
            new_name='patient_phone_number',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='p_previous_medical_history',
            new_name='patient_previous_medical_history',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='p_sex',
            new_name='patient_sex',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='p_smoking',
            new_name='patient_smoking',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='p_weight',
            new_name='patient_weight',
        ),
    ]
