# Generated by Django 3.2.19 on 2023-06-16 06:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0002_auto_20230616_1130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medications',
            name='medication_id',
        ),
        migrations.AlterField(
            model_name='medications',
            name='case_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.case'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='medications',
            name='doctor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
        migrations.AlterField(
            model_name='medications',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='medications',
            name='patient_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.patient'),
            preserve_default=False,
        ),
    ]
