# Generated by Django 3.2.19 on 2023-06-13 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20230613_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='patient_blood_pressure',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='patient_body_temprature',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='patient_pulse',
            field=models.IntegerField(null=True),
        ),
    ]
