# Generated by Django 3.2.19 on 2023-06-14 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20230614_1040'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_id', models.IntegerField()),
                ('doctor_name', models.CharField(max_length=100)),
                ('doctor_email', models.EmailField(max_length=100)),
                ('doctor_designation', models.CharField(max_length=100)),
                ('doctor_hospital_name', models.CharField(max_length=100)),
                ('doctor_hospital_location', models.CharField(max_length=100)),
                ('doctor_education', models.CharField(max_length=100)),
                ('doctor_mobile', models.CharField(max_length=10)),
            ],
        ),
    ]
