# Generated by Django 4.2.2 on 2023-06-14 18:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0007_case'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medication_id', models.IntegerField()),
                ('medication_name', models.CharField(max_length=100)),
                ('medication_dosage', models.CharField(max_length=700)),
                ('medication_duration', models.IntegerField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('case_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.case')),
                ('doctor_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('patient_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.patient')),
            ],
            options={
                'ordering': ['-updated', '-created'],
            },
        ),
    ]
