# Generated by Django 4.2.2 on 2023-06-14 19:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0008_medications'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_designation', models.CharField(max_length=100)),
                ('doctor_education', models.CharField(max_length=100)),
                ('doctor_hospital', models.CharField(max_length=100)),
                ('doctor_location', models.CharField(max_length=100)),
                ('doctor_phone_number', models.CharField(max_length=10)),
                ('doctor_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
